export enum IconLink {
	TEST = 'img/icons/ui/test.svg',
	PLUS = 'img/icons/ui/plus.svg',
	CROSS = 'img/icons/ui/cross.svg',
	MINUS = 'img/icons/ui/minus.svg',
	BACK = 'img/icons/ui/back.svg',
	SEARCH = 'img/icons/ui/search.svg',
	MENU = 'img/icons/ui/menu.svg',
	FROM = 'img/icons/ui/from.svg',
	TO = 'img/icons/ui/to.svg',
	SWAP = 'img/icons/ui/swap.svg',
	STEP1 = 'img/icons/ui/step1.svg',
	PROBLEM = 'img/icons/ui/problem.svg',
	ABOUT = 'img/icons/ui/about.svg',
	SETTINGS = 'img/icons/ui/settings.svg',
	HEART = 'img/icons/ui/heart.svg',
	LOCATIONS = 'img/icons/ui/building.svg',
	ARROW_UP = 'img/icons/ui/arrow-up.svg',
	ARROW_DOWN = 'img/icons/ui/arrow-down.svg',
	ARROW_LEFT = 'img/icons/ui/arrow-left.svg',
	ARROW_RIGHT = 'img/icons/ui/arrow-right.svg',
	SMILE_SAD = 'img/icons/ui/Smile-sad.svg',

	LEGAL = 'img/icons/plans/legal.svg',
	STUDY = 'img/icons/plans/study.svg',
	WOMAN = 'img/icons/plans/woman.svg',
	MEN = 'img/icons/plans/men.svg',
	WC = 'img/icons/plans/wc.svg',
	ENTER = 'img/icons/plans/enter.svg',
	FOOD = 'img/icons/plans/food.svg',
	BOOK = 'img/icons/plans/book.svg',
	ACT = 'img/icons/plans/act.svg',
	COWORKING = 'img/icons/plans/coworking.svg',
	SPORT = 'img/icons/plans/sport.svg',
	CROSSING = 'img/icons/plans/crossing.svg',
	ELEVATOR = 'img/icons/plans/elevator.svg',
	STAIR = 'img/icons/plans/stair.svg',
	GARDEROB = 'img/icons/plans/garderob.svg',

}
